### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by Kattur** [BiologicalRecordsCentre/BRC#11]
Again, the new pages look really smart and it is much easier to see the various filtering options.

The 'Search' works well, but there is no longer a drop down list for the 'Keywords' 

Clicking on the top journal link, the 'Year' is showing as 999 rather than 'submitted'.

Also, could the list of authors be wrapped. When there are many authors, the author box gets quite big.

The list of 'term' options is shorter than on the live site and does not included any of the 'Scheme - ...' . However, I personally prefer the new shorter version!

**Comment by Kattur** [comment]
I see the schemes button now! :)

**Comment by BirenRathod** [comment]
@Kattur 
- Unfortunately to implement dropdown is not possible for 'keywords' fields because it has synced differently in new site. 
- I have replaced 9999 year as submitted because it doesn't accept text in numeric field. if you any have other idea of, how to display text let me know?
- you mean to trim authors list?
- I separated the term & scheme two different lists, so they display nicely.
